### ISSUE TITLE
Consolidate Location Between GitHub and Portfolio

### ISSUE THREAD

**Issue by anleac** [mboisvertdupras/home#10]
👋 a friendly hubber just dropping by.

I am submitting this bug report to request that the location listed on both your GitHub page and your portfolio be consolidated to match.

Currently, your portfolio states your location as Granby, Quebec, while your GitHub page states your location as Montreal, Quebec. This discrepancy may lead to confusion for recruiters and other potential employers, so I suggest that the locations be consolidated to match.

Thank you for your consideration!

**Comment by mboisvertdupras** [comment]
Thank you for the feedback! I apologize for this discrepancy.

I have now updated the details to reflect the correct location in both the portfolio and my GitHub page.

Cheers!
